[project]
name = "podnebnik-datasette"
version = "0.1"
description = "Podnebnik datasette"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasette == 0.65.*",
]

[dependency-groups]
build = [
    "colorama",
    "frictionless == 5.18.*",
    "invoke",
    "sqlite-utils",
]
