version: '3.4'
services:
  app:
    user: vscode

    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    environment:
      DJANGO_SETTINGS_MODULE: podnebnik.settings.devcontainer

    volumes:
      - ..:/website:cached

    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres:11.10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: podnebnik
    volumes:
       - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
